sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 0.10
  - 0.12
  - iojs

notifications:
  email:
    - medikoo+controller-router@medikoo.com

script: "npm test && npm run lint"
